{
    "cve": {
        "id": "CVE-2024-0229",
        "sourceIdentifier": "secalert@redhat.com",
        "published": "2024-02-09T07:16:00.107",
        "lastModified": "2024-02-09T07:16:00.107",
        "vulnStatus": "Received",
        "descriptions": [
            {
                "lang": "en",
                "value": "An out-of-bounds memory access flaw was found in the X.Org server. This issue can be triggered when a device frozen by a sync grab is reattached to a different master device. This issue may lead to an application crash, local privilege escalation (if the server runs with extended privileges), or remote code execution in SSH X11 forwarding environments."
            }
        ],
        "metrics": {
            "cvssMetricV31": [
                {
                    "source": "secalert@redhat.com",
                    "type": "Secondary",
                    "cvssData": {
                        "version": "3.1",
                        "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
                        "attackVector": "LOCAL",
                        "attackComplexity": "LOW",
                        "privilegesRequired": "LOW",
                        "userInteraction": "NONE",
                        "scope": "UNCHANGED",
                        "confidentialityImpact": "HIGH",
                        "integrityImpact": "HIGH",
                        "availabilityImpact": "HIGH",
                        "baseScore": 7.8,
                        "baseSeverity": "HIGH"
                    },
                    "exploitabilityScore": 1.8,
                    "impactScore": 5.9
                }
            ]
        },
        "weaknesses": [
            {
                "source": "secalert@redhat.com",
                "type": "Primary",
                "description": [
                    {
                        "lang": "en",
                        "value": "CWE-788"
                    }
                ]
            }
        ],
        "references": [
            {
                "url": "https://access.redhat.com/errata/RHSA-2024:0320",
                "source": "secalert@redhat.com"
            },
            {
                "url": "https://access.redhat.com/errata/RHSA-2024:0557",
                "source": "secalert@redhat.com"
            },
            {
                "url": "https://access.redhat.com/errata/RHSA-2024:0558",
                "source": "secalert@redhat.com"
            },
            {
                "url": "https://access.redhat.com/errata/RHSA-2024:0597",
                "source": "secalert@redhat.com"
            },
            {
                "url": "https://access.redhat.com/errata/RHSA-2024:0607",
                "source": "secalert@redhat.com"
            },
            {
                "url": "https://access.redhat.com/errata/RHSA-2024:0614",
                "source": "secalert@redhat.com"
            },
            {
                "url": "https://access.redhat.com/errata/RHSA-2024:0617",
                "source": "secalert@redhat.com"
            },
            {
                "url": "https://access.redhat.com/errata/RHSA-2024:0621",
                "source": "secalert@redhat.com"
            },
            {
                "url": "https://access.redhat.com/errata/RHSA-2024:0626",
                "source": "secalert@redhat.com"
            },
            {
                "url": "https://access.redhat.com/errata/RHSA-2024:0629",
                "source": "secalert@redhat.com"
            },
            {
                "url": "https://access.redhat.com/security/cve/CVE-2024-0229",
                "source": "secalert@redhat.com"
            },
            {
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2256690",
                "source": "secalert@redhat.com"
            }
        ]
    }
}