{
    "cve": {
        "id": "CVE-2022-48564",
        "sourceIdentifier": "cve@mitre.org",
        "published": "2023-08-22T19:16:31.927",
        "lastModified": "2023-10-11T23:15:10.140",
        "vulnStatus": "Modified",
        "descriptions": [
            {
                "lang": "en",
                "value": "read_ints in plistlib.py in Python through 3.9.1 is vulnerable to a potential DoS attack via CPU and RAM exhaustion when processing malformed Apple Property List files in binary format."
            }
        ],
        "metrics": {
            "cvssMetricV31": [
                {
                    "source": "nvd@nist.gov",
                    "type": "Primary",
                    "cvssData": {
                        "version": "3.1",
                        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
                        "attackVector": "NETWORK",
                        "attackComplexity": "LOW",
                        "privilegesRequired": "NONE",
                        "userInteraction": "REQUIRED",
                        "scope": "UNCHANGED",
                        "confidentialityImpact": "NONE",
                        "integrityImpact": "NONE",
                        "availabilityImpact": "HIGH",
                        "baseScore": 6.5,
                        "baseSeverity": "MEDIUM"
                    },
                    "exploitabilityScore": 2.8,
                    "impactScore": 3.6
                }
            ]
        },
        "weaknesses": [
            {
                "source": "nvd@nist.gov",
                "type": "Primary",
                "description": [
                    {
                        "lang": "en",
                        "value": "CWE-400"
                    }
                ]
            }
        ],
        "configurations": [
            {
                "nodes": [
                    {
                        "operator": "OR",
                        "negate": false,
                        "cpeMatch": [
                            {
                                "vulnerable": true,
                                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                                "versionEndExcluding": "3.7.7",
                                "matchCriteriaId": "4EED37C7-A681-40B6-BC79-A47AF7D9C495"
                            },
                            {
                                "vulnerable": true,
                                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                                "versionStartIncluding": "3.8.0",
                                "versionEndExcluding": "3.8.2",
                                "matchCriteriaId": "368003C0-1D3C-4A3D-A998-A2406DB72ACB"
                            },
                            {
                                "vulnerable": true,
                                "criteria": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
                                "versionStartIncluding": "3.9.0",
                                "versionEndExcluding": "3.9.1",
                                "matchCriteriaId": "B6D7EFB7-52A8-4C10-B5F9-6F599F94CDC7"
                            },
                            {
                                "vulnerable": true,
                                "criteria": "cpe:2.3:a:python:python:3.10.0:alpha1:*:*:*:*:*:*",
                                "matchCriteriaId": "D3A22303-914F-4EB6-9CCE-EE0D5EDB424B"
                            }
                        ]
                    }
                ]
            }
        ],
        "references": [
            {
                "url": "https://bugs.python.org/issue42103",
                "source": "cve@mitre.org",
                "tags": [
                    "Exploit",
                    "Issue Tracking",
                    "Patch",
                    "Vendor Advisory"
                ]
            },
            {
                "url": "https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html",
                "source": "cve@mitre.org"
            },
            {
                "url": "https://security.netapp.com/advisory/ntap-20230929-0009/",
                "source": "cve@mitre.org"
            }
        ]
    }
}